name: DL_CAR
channels:
  - plotly
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - astunparse=1.6.3
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=3.3.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - charls=2.2.0
  - cloudpickle=1.6.0
  - cmake=3.19.6
  - cryptography=3.4.7
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.5.1
  - dataclasses=0.8
  - decorator=5.0.7
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - entrypoints=0.3
  - expat=2.3.0
  - freetype=2.10.4
  - fsspec=0.9.0
  - future=0.18.2
  - giflib=5.1.4
  - icu=68.1
  - idna=2.10
  - imagecodecs=2021.4.28
  - imageio=2.9.0
  - importlib-metadata=4.0.1
  - intel-openmp=2021.2.0
  - ipykernel=5.5.3
  - ipympl=0.7.0
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.9.2
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.6.4
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.18.2
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - lerc=2.2.1
  - libaec=1.0.4
  - libcurl=7.71.1
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuv=1.40.0
  - libwebp=1.0.1
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - magma-cuda112=2.5.2
  - markupsafe=1.1.1
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-include=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - nbclassic=0.2.7
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.5
  - ninja=1.10.2
  - nodejs=12.19.0
  - notebook=6.3.0
  - numpy-base=1.20.1
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.12
  - pandocfilters=1.4.2
  - parso=0.8.2
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - plotly=4.14.3
  - plotly-orca=1.3.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=19.0.2
  - readline=8.1
  - requests=2.25.1
  - retrying=1.3.3
  - rhash=1.4.1
  - scikit-image=0.18.1
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.15.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlite=3.35.4
  - terminado=0.9.4
  - testpath=0.4.4
  - tifffile=2021.4.8
  - tk=8.6.10
  - tomlkit=0.7.0
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - box2d-py==2.3.8
    - dominate==2.6.0
    - geomloss==0.2.4
    - grad-cam==1.2.9
    - gym==0.18.3
    - imutils==0.5.4
    - jsonpatch==1.32
    - jsonpointer==2.1
    - kornia==0.5.3
    - numpy==1.20.2
    - opencv-python==4.5.2.52
    - pillow==7.2.0
    - pyglet==1.5.15
    - pykeops==1.5
    - pytorch-fid==0.2.0
    - torch==1.9.0a0+git2436377
    - torchfile==0.1.0
    - torchvision==0.10.0a0+f1d7342
    - ttach==0.0.3
    - visdom==0.1.8.9
    - websocket-client==0.59.0
